language: go

sudo: false

dist: trusty

go:
  - "1.10.1"

os:
  - linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rsync sshpass hugo

script:
  - ./hugo

after_success:
  - sshpass -p $SFTP_PASSWORD rsync -e "ssh -o StrictHostKeyChecking=no" -arvzc ./public/* $SFTP_USER@codeep.blue:/var/www
