language: go

sudo: false

dist: trusty

git:
  depth: false

go:
  - "1.10.1"
os:
  - linux
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rsync

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.38/hugo_0.38_Linux-64bit.tar.gz
  - tar xf ./hugo_0.38_Linux-64bit.tar.gz

script:
  - ./hugo

after_success:
  - sshpass -p $SFTP_PASSWORD rsync -arvzc ./public/* $SFTP_USER@codeep.blue:/var/www
