language: go

sudo: false

dist: trusty

git:
  depth: false

go:
  - "1.10.1"
os:
  - linux
  fast_finish: true

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.38/hugo_0.38_Linux-64bit.tar.gz
  - tar xf ./hugo_0.38_Linux-64bit.tar.gz

script:
  - ./hugo

after_success:
  - curl --ftp-create-dirs -T . sftp://${SFTP_USER}:${SFTP_PASSWORD}@codeep.blue/var/www
