baseURL = "https://codeep.blue/"
languageCode = "pt-br"
title = "Codeep.Blue"
googleAnalytics = "UA-108157905-1"
theme = "blue"
enableEmoji = true

[params]
subtitle = "desenvolvimento de software de forma simples e descomplicada"
recents = 3
contact = "contact@codeep.blue"
disqus = "codeepblue"
dateformat = "02/01/2006"
logo = "/image/logo.png"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

googlefonts = "https://fonts.googleapis.com/css?family=Open+Sans:400,700"
fontfamily = "Open Sans,sans-serif"
logofontfamily = "Open Sans,sans-serif"
pluralizeListTitles = false
rssLimit = 255

ampscripts = """
    <script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
    """

addthisscripts = """
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b168ba82fb0c41d"></script>
"""
