baseURL = "https://codeep.blue/"
languageCode = "pt-br"
title = "Codeep.Blue"
googleAnalytics = "UA-108157905-1"
theme = "blue"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[params]
subtitle = "Desenvolvimento de software descomplicado"
description = "Desenvolvimento de sistemas. Monitoramento de servidores. Consultoria de projetos de software. Criação de sites. Tudo para você e sua empresa. Solicite aqui."
recents = 3
contact = "contact@codeep.blue"
disqus = "codeepblue"
dateformat = "02/01/2006"
logo = "/image/logo.png"

businessLocality = "Blumenau"
businessRegion = "Santa Catarina"
businessCountryName = "Brazil"

googlefonts = "https://fonts.googleapis.com/css?family=Open+Sans:400,700"
fontfamily = "Open Sans,sans-serif"
logofontfamily = "Open Sans,sans-serif"
pluralizeListTitles = false
rssLimit = 255

ampscripts = """
    <script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
    """

jsonld = """
{
  "@context": "http://schema.org/",
  "@type": "Organization",
  "name": "Codeep.Blue",
  "address": {
  "@type": "PostalAddress",
    "streetAddress": "",
    "addressLocality": "Blumenau",
    "addressRegion": "Santa Catarina",
    "postalCode": ""
  },
  "telephone": ""
}
"""
