name = "Blue"
license = "MIT"
licenselink = "https://github.com/codeepblue/blue/blob/master/LICENSE.md"
description = "Theme for Hugo that supports the Accelerated Mobile Pages Project(AMP)."
homepage = "https://github.com/codeepblue/blue"
tags = ["blog", "amp", "disqus"]
features = ["amp", "responsive", "seo", "thumbnail", "share button", "structured data", "ogp", "twitter cards", "github_cards"]
min_version = 0.16

[author]
  name = "Jonathan A. Schweder"
  homepage = "https://codeep.blue"

